### ISSUE TITLE
plagiarize fails with assertion error

### ISSUE THREAD

**Issue by Endeavour-BRM** [jkob/quillbot-plagiarizer#1]
Hi,

I tried using this utility, after inputting the sentence its failing with below error

Error: AssertionError [ERR_ASSERTION]: No node found for selector: .paraphrase-btn

Can you please tell me where I am going wrong.

Thanks and Regards
Aanjan Hari

**Comment by Endeavour-BRM** [comment]
seems to be button selector is now updated to .paraphrase-btn-dem.
Closing the issue.

**Comment by Endeavour-BRM** [comment]
@jkob This method takes some time to return the result, is there any other solution like API calls get response sooner.

**Comment by jkob** [comment]
The method takes a long time because it fires up a Chrome headless window.

A easy way to fix that is to put this Puppeteer controller in a backend and
open that up for API calls. But that was too much of a hassle during
creating this, that I chose to not mind the long delay.

If you need suggestions how to solve it, let me know.

**Comment by jkob** [comment]
hey @Endeavour-BRM 

You made me realize that I dont need Puppeteer & headless Chrome. 
I'm currently working on a new version that will remove that dependency.

I also fixed the issue with the selector.
Thank you for reporting the issue.
